run:
  timeout: 5m
  go: "1.26"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/muliwe/go-client-classifier
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
