version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - gocritic
    - misspell
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/muliwe/go-client-classifier
  exclusions:
    generated: lax
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
